# ----------------------------
# Makefile Options
# ----------------------------

NAME = CMAZE
ICON = icon.png
DESCRIPTION = "70s style maze game for the TI-84"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -O2
CXXFLAGS = -Wall -Wextra -O2

# ----------------------------

include $(shell cedev-config --makefile)
